name: Build and Test

on:
  push:
  pull_request:
    branches: [master]
env:
  DOTNET_VERSION: '9.0.x'
jobs:
  build:
    name: ci-${{matrix.os}}
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macos-x64', 'macos-arm64']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macos-x64
            os: macos-latest
            target: osx-x64
          - kind: macos-arm64
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
            dotnet restore
            dotnet build 2FA --runtime ${{ matrix.target }} --configuration Release --self-contained false

      - name: Test
        run: dotnet test --no-restore --verbosity normal
